name: Docker Image CI
on:
  push:
    branches: [ '**' ]
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    strategy:
      matrix:
        image:
          - idris2
          - idris2api
    runs-on: ubuntu-latest
    env:
      PUSH_IMAGES: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        path: main
    - name: Checkout idris2 repo
      uses: actions/checkout@v2
      with:
        repository:  idris-lang/Idris2
        path: Idris2
        fetch-depth: 0
    - name: Build the ${{ matrix.image }} Docker image
      run: |
        cp main/${{ matrix.image }}.Dockerfile Idris2/
        cd Idris2/
        docker build . --file ${{ matrix.image }}.Dockerfile --tag snazzybucket/${{ matrix.image }}:latest
        docker tag snazzybucket/${{ matrix.image }}:latest snazzybucket/${{ matrix.image }}:$(git describe --tags)
    - name: Login to DockerHub
      if: ${{ env.PUSH_IMAGES }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the ${{ matrix.image }} Docker image
      if: ${{ env.PUSH_IMAGES }}
      run: |
        cd Idris2/
        docker push snazzybucket/${{ matrix.image }}:latest
        docker push snazzybucket/${{ matrix.image }}:$(git describe --tags)
