name: Docker Image CI
on:
  push:
    branches: [ '**' ]
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    strategy:
      matrix:
        image:
          - idris2
          - idris2api
    runs-on: ubuntu-latest
    env:
      PUSH_IMAGES: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        path: main
        fetch-depth: 0

    - name: Checkout idris2 repo
      uses: actions/checkout@v2
      with:
        repository:  idris-lang/Idris2
        path: Idris2
        fetch-depth: 0

    - uses: dhall-lang/setup-dhall@v4

    - name: set the DOCKER_TAG version
      run: |
        cd Idris2/
        echo "DOCKER_TAG=$(git describe --tags)" >> $GITHUB_ENV
        cd ../

    - name: Build the ${{ matrix.image }} Docker image
      run: |
        cp main/${{ matrix.image }}.Dockerfile Idris2/
        cd Idris2/
        docker build . --file ${{ matrix.image }}.Dockerfile --tag snazzybucket/${{ matrix.image }}:latest
        docker tag snazzybucket/${{ matrix.image }}:latest snazzybucket/${{ matrix.image }}:$DOCKER_TAG

    - name: Login to DockerHub
      if: ${{ env.PUSH_IMAGES }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the ${{ matrix.image }} Docker image
      if: ${{ env.PUSH_IMAGES }}
      run: |
        cd Idris2/
        docker push snazzybucket/${{ matrix.image }}:latest
        docker push snazzybucket/${{ matrix.image }}:$DOCKER_TAG

    - name: setup git config
      if: ${{ env.PUSH_IMAGES }}
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "<>"

    - name: commit and push README changes
      if: ${{ env.PUSH_IMAGES }}
      run: |
        # Stage the file, commit and push
        cd main

        echo $DOCKERTAG
        dhall version
        cat README.dhall | dhall text > README.md
        git add README.md
        git commit -m "[skip ci] Update docker tag in README.md"
        git show
        git push origin main
        cd ../
