name: Docker Image CI
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: master
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository:  idris-lang/Idris2
        path: idris2
        fetch-depth: 0
    - name: Build the Docker image
      run: |
        cp master/Dockerfile idris2/
        cd idris2/
        docker build . --file Dockerfile --tag snazzybucket/idris2:latest
        docker tag snazzybucket/idris2:latest snazzybucket/idris2:$(git describe --tags)
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the Docker image
      run: |
        cd idris2/
        docker push snazzybucket/idris2:latest
        docker push snazzybucket/idris2:$(git describe --tags)
